name: Deploy to Live  

on:
  workflow_dispatch: # Manual trigger for deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LIVE_HOST }} # Server IP
          username: ${{ secrets.LIVE_USERNAME }} # SSH username
          key: ${{ secrets.LIVE_SSH_PRIVATE_KEY }} # SSH private key
         
