name: Build & Deploy Live

on:
  # push:
    # branches: [main]
  workflow_dispatch: # Manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Live CG Staging
        uses: appleboy/ssh-action@master

        with:
          host: ${{ secrets.LIVE_HOST }} # Your server's IP address
          username: ${{ secrets.LIVE_USERNAME }} # Your server's username
          key: ${{ secrets.LIVE_SSH_PRIVATE_KEY }} # Your server's SSH private key
          